"""initial schema

Revision ID: 31d2517b11b6
Revises: 
Create Date: 2026-09-25 16:30:28.048738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31d2517b11b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('auto_approve_threshold', sa.Float(), nullable=False),
    sa.Column('downtime_cost_per_hour_inr', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('auto_approve_threshold >= 0 AND auto_approve_threshold <= 1', name='ck_plant_threshold_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_plant_tenant_code')
    )
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plants_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('machines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('plant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('asset_code', sa.String(length=64), nullable=False),
    sa.Column('line', sa.String(length=100), nullable=True),
    sa.Column('machine_type', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_id', 'asset_code', name='uq_machine_plant_code')
    )
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.create_index('ix_machine_plant_active', ['plant_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_machines_plant_id'), ['plant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_machines_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('raw_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('plant_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('reporter', sa.String(length=200), nullable=True),
    sa.Column('source_metadata', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_raw_source_external')
    )
    with op.batch_alter_table('raw_records', schema=None) as batch_op:
        batch_op.create_index('ix_raw_plant_received', ['plant_id', 'received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_records_plant_id'), ['plant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_records_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('machine_aliases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('plant_id', sa.String(length=36), nullable=False),
    sa.Column('machine_id', sa.String(length=36), nullable=False),
    sa.Column('alias_text', sa.String(length=300), nullable=False),
    sa.Column('normalized_text', sa.String(length=300), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_id', 'normalized_text', name='uq_alias_plant_text')
    )
    with op.batch_alter_table('machine_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_machine_aliases_machine_id'), ['machine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_machine_aliases_normalized_text'), ['normalized_text'], unique=False)
        batch_op.create_index(batch_op.f('ix_machine_aliases_plant_id'), ['plant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_machine_aliases_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('staged_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('plant_id', sa.String(length=36), nullable=False),
    sa.Column('raw_record_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=True),
    sa.Column('machine_text', sa.String(length=300), nullable=True),
    sa.Column('machine_id', sa.String(length=36), nullable=True),
    sa.Column('failure_mode', sa.String(length=200), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('parts', sa.JSON(), nullable=False),
    sa.Column('downtime_hours', sa.Float(), nullable=True),
    sa.Column('technician', sa.String(length=200), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('field_confidence', sa.JSON(), nullable=False),
    sa.Column('resolution_confidence', sa.Float(), nullable=False),
    sa.Column('resolution_method', sa.String(length=20), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=False),
    sa.Column('review_reasons', sa.JSON(), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('llm_input_tokens', sa.Integer(), nullable=False),
    sa.Column('llm_output_tokens', sa.Integer(), nullable=False),
    sa.Column('llm_latency_ms', sa.Integer(), nullable=False),
    sa.Column('llm_cost_inr', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_records.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staged_records', schema=None) as batch_op:
        batch_op.create_index('ix_staged_plant_status', ['plant_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_staged_records_machine_id'), ['machine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staged_records_plant_id'), ['plant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staged_records_raw_record_id'), ['raw_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staged_records_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('maintenance_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('plant_id', sa.String(length=36), nullable=False),
    sa.Column('raw_record_id', sa.String(length=36), nullable=False),
    sa.Column('staged_record_id', sa.String(length=36), nullable=True),
    sa.Column('machine_id', sa.String(length=36), nullable=True),
    sa.Column('occurred_on', sa.Date(), nullable=True),
    sa.Column('machine_text', sa.String(length=300), nullable=True),
    sa.Column('failure_mode', sa.String(length=200), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('parts', sa.JSON(), nullable=False),
    sa.Column('downtime_hours', sa.Float(), nullable=True),
    sa.Column('technician', sa.String(length=200), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('downtime_hours IS NULL OR downtime_hours >= 0', name='ck_record_downtime_non_negative'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_records.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['staged_record_id'], ['staged_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_records_failure_mode'), ['failure_mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_records_machine_id'), ['machine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_records_occurred_on'), ['occurred_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_records_plant_id'), ['plant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_records_raw_record_id'), ['raw_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_records_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_record_plant_machine_date', ['plant_id', 'machine_id', 'occurred_on'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_records', schema=None) as batch_op:
        batch_op.drop_index('ix_record_plant_machine_date')
        batch_op.drop_index(batch_op.f('ix_maintenance_records_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_records_raw_record_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_records_plant_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_records_occurred_on'))
        batch_op.drop_index(batch_op.f('ix_maintenance_records_machine_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_records_failure_mode'))

    op.drop_table('maintenance_records')
    with op.batch_alter_table('staged_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staged_records_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_staged_records_raw_record_id'))
        batch_op.drop_index(batch_op.f('ix_staged_records_plant_id'))
        batch_op.drop_index(batch_op.f('ix_staged_records_machine_id'))
        batch_op.drop_index('ix_staged_plant_status')

    op.drop_table('staged_records')
    with op.batch_alter_table('machine_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machine_aliases_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_machine_aliases_plant_id'))
        batch_op.drop_index(batch_op.f('ix_machine_aliases_normalized_text'))
        batch_op.drop_index(batch_op.f('ix_machine_aliases_machine_id'))

    op.drop_table('machine_aliases')
    with op.batch_alter_table('raw_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_records_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_raw_records_plant_id'))
        batch_op.drop_index('ix_raw_plant_received')

    op.drop_table('raw_records')
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machines_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_machines_plant_id'))
        batch_op.drop_index('ix_machine_plant_active')

    op.drop_table('machines')
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plants_tenant_id'))

    op.drop_table('plants')
    # ### end Alembic commands ###
